project:
  language: terraform

deploy:
  aws:
    dev:
      account: "939558410024"
      region: "sa-east-1"
    config:
      account: "391738926627"

infra:
  terraform:
    working-directory: "./infra"
    node-version: "16"
    version: "1.12.2"
    log-trace: "false"
    destroy: "false"
    custom-role: "GitHubActions-Terraform"