name: "01 - [FEAT] Build & Pull Request"

on:
    push:
        branches:
            - 'feature**'
    workflow_dispatch:

jobs:
    infra:
        uses: org-wantoli/up-nested-reusable-infra-terraform/.github/workflows/feature.yml@main
        secrets: inherit