name: "01 - [FEAT] Build & PR"

on:
    push:
        branches:
            - 'feature**'

jobs:
    infra:
        uses: wantoli/up-nested-reusable-infra-terraform/.github/workflows/feature.yml@v1
        secrets: inherit